name: React with webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Setup git
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git log
        git checkout feat
    - name: Create report file
      run: date +%s > report.txt
    - name: Commit report
      run: |
        git status
        git add report.txt
        git status
        git commit -am "Automated report"
        git status
        git log
        git push -u origin feat
